// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9SdbMHsoNXEV-wJah8l2Oc5huQK_Kol4',
    appId: '1:1012846137817:web:78e7233633e0b591ca49c8',
    messagingSenderId: '1012846137817',
    projectId: 'augustinsam-41e6d',
    authDomain: 'augustinsam-41e6d.firebaseapp.com',
    databaseURL: 'https://augustinsam-41e6d.firebaseio.com',
    storageBucket: 'augustinsam-41e6d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEjnOrfYIE6vcAEu8KG1aH9FQ7S0hhs1Q',
    appId: '1:1012846137817:android:1ca550d4bf25358dca49c8',
    messagingSenderId: '1012846137817',
    projectId: 'augustinsam-41e6d',
    databaseURL: 'https://augustinsam-41e6d.firebaseio.com',
    storageBucket: 'augustinsam-41e6d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxMOYR8plFk_uRQIVNV6kEbgAYb79tALc',
    appId: '1:1012846137817:ios:a6e86e91f9eb365dca49c8',
    messagingSenderId: '1012846137817',
    projectId: 'augustinsam-41e6d',
    databaseURL: 'https://augustinsam-41e6d.firebaseio.com',
    storageBucket: 'augustinsam-41e6d.firebasestorage.app',
    iosBundleId: 'com.example.rareCrew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxMOYR8plFk_uRQIVNV6kEbgAYb79tALc',
    appId: '1:1012846137817:ios:a6e86e91f9eb365dca49c8',
    messagingSenderId: '1012846137817',
    projectId: 'augustinsam-41e6d',
    databaseURL: 'https://augustinsam-41e6d.firebaseio.com',
    storageBucket: 'augustinsam-41e6d.firebasestorage.app',
    iosBundleId: 'com.example.rareCrew',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB9SdbMHsoNXEV-wJah8l2Oc5huQK_Kol4',
    appId: '1:1012846137817:web:ac60bdfbe8159739ca49c8',
    messagingSenderId: '1012846137817',
    projectId: 'augustinsam-41e6d',
    authDomain: 'augustinsam-41e6d.firebaseapp.com',
    databaseURL: 'https://augustinsam-41e6d.firebaseio.com',
    storageBucket: 'augustinsam-41e6d.firebasestorage.app',
  );
}
